### ISSUE TITLE
Artifacts example

### ISSUE THREAD

**Issue by tachyus-ryan** [argoproj-labs/hera-workflows#10]
Would you mind sharing how one might use input and output artifacts with hera? Is that possible?

**Comment by flaviuvadan** [comment]
> Would you mind sharing how one might use input and output artifacts with hera? Is that possible?

Hey @tachyus-ryan! Thanks for the question. Artifacts are not currently implemented in Hera. It's quite a stripped down version of Argo Workflows for now. The project aimed to see whether the community would want specific things implemented, such as artifacts, and then implement those with helper methods/approaches to simplify accessibility. Are you interested in contributing this? If you may not have the time, any chance you can submit an issue classified as a feature enhancement so we can introduce it to Hera? 🙂

**Comment by tachyus-ryan** [comment]
I'm afraid I don't have a lot of time to contribute just now, but I'll take a look.

**Comment by panesofglass** [comment]
I cannot get the environment set up with `pipenv` either on Windows or Ubuntu. I'll see about creating another issue or reformatting this one in the form of a feature enhancement.

**Comment by flaviuvadan** [comment]
> I cannot get the environment set up with `pipenv` either on Windows or Ubuntu. I'll see about creating another issue or reformatting this one in the form of a feature enhancement.

Oh, that's interesting! What sort of issues are you encountering?

**Comment by panesofglass** [comment]
I get an error that `choose_shell` is missing parameter `project` in both environments.

**Comment by flaviuvadan** [comment]
> choose_shell

Do you happen to have the latest version of `pipenv`? I see an issue filed with it from a few days ago that has to do with a `choose_shell` [error](https://github.com/pypa/pipenv/issues/4828).

**Comment by tachyus-ryan** [comment]
@flaviuvadan I was using the latest version. I'll try an earlier version.

**Comment by tachyus-ryan** [comment]
See #13.
