### ISSUE TITLE
Coin_flip by task status.

### ISSUE THREAD

**Issue by Kobidav** [argoproj-labs/hera-workflows#111]
Hello!
Could you please add "when" for tasks and workflow status ( Succeeded, Failed, Error), like exit handler task.
E.G. for tasks, this working for me:

```
  def when_status(self, other: 'Task', operator: Operator, value: str) -> 'Task':
      self.argo_task.when = f'{{{{tasks.{other.name}.status}}}} {operator.value} {value}'
      return other.next(self)
```
and 

```
r = Task("r", random_code)
h = Task("h", heads)
t = Task("t", tails)

h.when_status(r, Operator.equals, "Succeeded")
t.when_status(r, Operator.equals, "Failed")

```

**Comment by flaviuvadan** [comment]
Thank you for submitting this @Kobidav! This is similar to the current `when` implementation, so it is fairly easy to add, as you suggested! I am going to mark this as an enhancement.

**Comment by flaviuvadan** [comment]
@Kobidav I am thinking about another possible interface for this:
```python
class Task(...):

    def on_success(self, other: 'Task'): ...  # launch other on success of self

    def on_failure(self, other: 'Task'): ...  # launch other on failure of self

    def on_error(self, other: 'Task'): ...  # launch other on error of self
```

Thoughts? I wonder if this interface provides a nice separation between the `when`, which is a conditional on multiple operators, such as `eq`, `neq`, `gt`, etc, whereas the status based execution is based on these 3 pre-defined Argo conditions.

**Comment by flaviuvadan** [comment]
Added: https://github.com/argoproj-labs/hera-workflows/pull/113
