### ISSUE TITLE
How should private container registry credentials be specified (e.g. ImagePullSecret)

### ISSUE THREAD

**Issue by spdjudd** [argoproj-labs/hera-workflows#112]
Hi, 
I have a question on how we should provide credentials for private container registries.  In Argo we specify `imagePullSecrets` in our Workflow spec, but can you help me out with how to do this in Hera?
Thanks!
Simon.

**Comment by flaviuvadan** [comment]
Hi @spdjudd! Thanks for submitting the question! This is something that Hera does not currently support but it's an addition that is not very complex, based on Argo's example: https://github.com/argoproj/argo-workflows/blob/master/examples/image-pull-secrets.yaml 

Until Hera supports this, your use case probably necessitates something like:
```python
w = Workflow(...)
setattr(w.spec, 'imagePullSecrets', [{'name': 'my-secret'}])

t = Task(..., image='my-private-image:latest')
w.add_task(t)
w.create()
```

**Comment by spdjudd** [comment]
Hi Flaviu, thanks very much for the prompt and helpful response!  I'll give that a try.

**Comment by spdjudd** [comment]
Wow, quick work on the PR - thanks!  I tried your snippet above and found I had to use `LocalObjectReference` instead of a dictionary to avoid serialisation errors, and this worked:

```
w = Workflow(...)
w.spec.set_attribute('imagePullSecrets', [LocalObjectReference(name='my-secret')])

t = Task(..., image='my-private-image:latest')
w.add_task(t)
w.create()
```

**Comment by flaviuvadan** [comment]
> Wow, quick work on the PR - thanks! I tried your snippet above and found I had to use `LocalObjectReference` instead of a dictionary to avoid serialisation errors, and this worked:
> 

Yes, I noticed that when I started implementing it! Apologies for the error in the suggestion. Going to merge the PR soon if you agree it's the right approach and solves the use case you have! 🙂

**Comment by spdjudd** [comment]
Looks good and definitely solves my use case - thanks again!

**Comment by flaviuvadan** [comment]
Added: https://github.com/argoproj-labs/hera-workflows/pull/113
