### ISSUE TITLE
How to use workflow-template in Task ?

### ISSUE THREAD

**Issue by szdr** [argoproj-labs/hera-workflows#117]
In argo-workflows, workflow-template can be used by specifying a templateRef in the WorkflowStep.
https://github.com/argoproj/argo-workflows/blob/master/examples/workflow-template/steps.yaml#L11-L13

How is this accomplished in hera-workflows?

**Comment by flaviuvadan** [comment]
Hi @szdr! Hera currently [supports workflow template references on workflows](https://github.com/argoproj-labs/hera-workflows/blob/main/examples/workflow_with_template_ref.py) only but not through tasks. I believe [this issue](https://github.com/argoproj-labs/hera-workflows/issues/88) may cover the feature you need?

**Comment by szdr** [comment]
@flaviuvadan 
Thanks for the reply!

In my situation, I assume that the administrator prepares a ClusterWorkflowTemplate that contains multiple templates, and the user calls the template in the ClusterWorkflowTemplate by templateRef from a step in their own workflow.
Unfortunately, I don't think it would be suitable for my use, since the workflow-of-workflows assumes the use of WorkflowTemplateRef.

**Comment by flaviuvadan** [comment]
Ah, I see, so the task is the one that's supposed to use a specific template, correct? If so, we may need to add template references to tasks, [as in this example](https://github.com/argoproj/argo-workflows/blob/master/examples/workflow-template/dag.yaml), maybe?

**Comment by szdr** [comment]
> Ah, I see, so the task is the one that's supposed to use a specific template, correct?

That's right!

> If so, we may need to add template references to tasks, [as in this example](https://github.com/argoproj/argo-workflows/blob/master/examples/workflow-template/dag.yaml), maybe?

That's exactly the feature I want.

**Comment by flaviuvadan** [comment]
Got it! I am glad we reached an agreement! 🚀 I marked this issue as an enhancement and I will try to get to it this upcoming weekend. I will tag you on the PR!
