### ISSUE TITLE
Support input from parameters not only output artifacts (orig: How to get output parameters from output file instead of stdout?)

### ISSUE THREAD

**Issue by xiang9156** [argoproj-labs/hera-workflows#120]
Hi,

Sometimes we define output parameters from a json file like this:
![image](https://user-images.githubusercontent.com/14140862/161964132-162f3b23-af3b-4ae7-a4a9-565d91afe539.png)
Is it supported by hera?

Thanks

**Comment by flaviuvadan** [comment]
Hello @xiang9156! Yes, one can use input/output artifacts for passing files between tasks. [Here's](https://github.com/argoproj-labs/hera-workflows/blob/main/examples/artifact_with_fanout.py) an example 🙂  In that example the `writer` writes a file to a specific path, which is listed as an `OutputArtifact`, then the consumer reads that file, which is listed as an `InputArtifact`.

**Comment by xiang9156** [comment]
> Hello @xiang9156! Yes, one can use input/output artifacts for passing files between tasks. [Here's](https://github.com/argoproj-labs/hera-workflows/blob/main/examples/artifact_with_fanout.py) an example 🙂 In that example the `writer` writes a file to a specific path, which is listed as an `OutputArtifact`, then the consumer reads that file, which is listed as an `InputArtifact`.

Thank you @flaviuvadan for the reply. Right now we are using the output **parameters** instead of artifacts, so that we can refer the json parameter like this `"{{=jsonpath(tasks['entry'].outputs.parameters.result, '$.result.job_id')}}"` , I checked the examples you shared, looks like it needs a middle layer to read the output artifact and print it to stdout.

**Comment by flaviuvadan** [comment]
Ah, got it, so this is a feature enhancement we need to do: support input from parameters not only output artifacts!

**Comment by MichaelLan** [comment]
Hello, at the moment I have created a wrapper for the Task class, for now it's working for me, I would like work in this feature, but I don't know if internally they are already working on it.

In this comment you can see my implementation, still under construction.
https://github.com/argoproj-labs/hera-workflows/issues/138#issuecomment-1120286397
