### ISSUE TITLE
[BUG] Wrong order of next() in `Task.when()`, `Task.on_success`, `Task.on_failure`

### ISSUE THREAD

**Issue by RunningIkkyu** [argoproj-labs/hera-workflows#128]
Shall we change this line to  `return self.next(other)` ?  
https://github.com/argoproj-labs/hera-workflows/blob/ebd7ac27ce26328f1de4bc669b4d0c710f11dd5e/src/hera/task.py#L375

So as the return statements in `when()`, `on_failure()`.

**Comment by flaviuvadan** [comment]
Addressed in https://github.com/argoproj-labs/hera-workflows/pull/129
