### ISSUE TITLE
Retry a succeeded task

### ISSUE THREAD

**Issue by bnuzhanyu** [argoproj-labs/hera-workflows#141]
Suppose I have a workflow of task A, B, C.
* A cost 1 day to produce some data for B.
* B execute some code from git to produce output for C.
* C process B's output
After execution, A/B is success and C is failed. I found B has a little bug and fix that code.
Now I want to skip A and re-execute B again. Can I have a way to do this?
Though it's not a reasonable petition for workflow, but debugging could be easy if it is implemented.

**Comment by flaviuvadan** [comment]
Hello @bnuzhanyu! This is a good question and.. I am not sure. I know Argo recently added [debug pause](https://argoproj.github.io/argo-workflows/debug-pause/) but it does not seem to satisfy the use case here. Perhaps two other options are:
- modify the workflow to not include task A
- use [memoization](https://argoproj.github.io/argo-workflows/memoization/) to cache the result of A so you can resubmit the workflow with the bug fix for B to run C but skip A during execution because the result is cached. Argo will see the cached result and not execute the step. It will still show up in the UI, I believe

**Comment by kromanow94** [comment]
What about adding additional parameter to the tasks, lets say `skip`, and just exit from the function? As far as I know Argo doesn't support retrying successful tasks. Is resubmitting an option?

**Comment by szdr** [comment]
How about inserting a step to check if the file to be generated by task A exists?
If the file exists, skip execution of task A.

```python
ws = WorkflowService(
    host=host,
    token=token,
    namespace=namespace,
)

w = Workflow(
    "skip_conditional",
    ws,
    namespace=namespace,
    service_account_name=service_account,
)

def is_exist_file():
    print("exist_true")

def A():
    print("A cost 1day to produce some data for B.")

def B():
    print("produce output for C.")

def C():
    print("process B's output")

is_exist_file_task = Task(name="is_exist_file", func=is_exist_file, image=image)
a_task = Task(name="A", func=A, image=image)
a_task.when(is_exist_file_task, Operator.not_equal, "exist_true")
b_task = Task(name="B", func=B, image=image)
c_task = Task(name="C", func=C, image=image)

is_exist_file_task >> a_task >> b_task >> c_task
w.add_tasks(is_exist_file_task, a_task, b_task, c_task)
w.create()
```

```
STEP                 TEMPLATE          PODNAME                      DURATION  MESSAGE
 ✔ skip-conditional  skip-conditional
 ├─✔ is-exist-file   is-exist-file     skip-conditional-403606110   11s
 ├─○ A               A                                                        when 'exist_true != exist_true' evaluated false
 ├─✔ B               B                 skip-conditional-1736041191  10s
 └─✔ C               C                 skip-conditional-1719263572  12s
```

**Comment by flaviuvadan** [comment]
@szdr I believe that is [memoization](https://argoproj.github.io/argo-workflows/memoization/), which is supported by Argo Workflows! Would that solve for this use case?
