### ISSUE TITLE
Problem with string parameters

### ISSUE THREAD

**Issue by vikramsg** [argoproj-labs/hera-workflows#162]
Hi, 

I am experimenting with using Hera and came across an issue. I have 2 tasks. The first task dumps out the parameters with which the second task can fan out. When I try to do this with only 1 parameter, it works fine. Even with 2 parameters it works fine, if both parameters used are `int`. Below is a working example. 

```
def generate():
    chunk_number_list = list(range(0, 10))
    json.dump([{"chunk_number": chunk_number, "chunk": chunk_number} for chunk_number in chunk_number_list], sys.stdout)

def consume(chunk_number, chunk):
    print(chunk_number, chunk)

consume_task = Task(
    "consume",
    consume,
    input_from=InputFrom(name="generate", parameters=["chunk_number", "chunk"]),)
```

But when I change the `generate` to output a string, I get an error.

```
def generate():
    chunk_number_list = list(range(0, 10))
    json.dump([{"chunk_number": chunk_number, "chunk": "s"} for chunk_number in chunk_number_list], sys.stdout)
```

The error is
```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Any pointers on what the issue may be? Thanks for the help.

**Comment by flaviuvadan** [comment]
Hello @vikramsg! Thank you for submitting the issue 🙂  We've identified this issue internally at @dynotx as we also pass string parameters between jobs. The main reason is the the string needs to be JSON encoded in order for decoding to work. I have a fix for this that does not require users to perform any sort of string encoding themselves. I will mark this issue as a bug report and will deploy the fix in 3.3, which has a PR open. I will tag you in the PR that provides the fix and will try your specific example as a test.
