### ISSUE TITLE
How do you specify the service account to run the workflow?

### ISSUE THREAD

**Issue by tachyus-ryan** [argoproj-labs/hera-workflows#17]
I would like to run the workflow as a non-default service account. However, I don't see a way to specify the service account to use. Is this supported?

**Comment by flaviuvadan** [comment]
> I would like to run the workflow as a non-default service account. However, I don't see a way to specify the service account to use. Is this supported?

Thanks for the issue submission @tachyus-ryan! This is not supported yet but it's a very quick addition! I can add it for you today.

**Comment by dmerrick** [comment]
This would be valuable to me as well

**Comment by flaviuvadan** [comment]
I just created #18 to add the service account name to workflows!

**Comment by flaviuvadan** [comment]
Fixed by #18
