### ISSUE TITLE
How do you add an emptyDir volume?

### ISSUE THREAD

**Issue by tachyus-ryan** [argoproj-labs/hera-workflows#19]
I would like to add an `emptyDir` volume as a temporary working volume. Is that possible or do I need to add a standard volume?

**Comment by tachyus-ryan** [comment]
Found it:

```
from hera.v1.empty_dir_volume import EmptyDirVolume
from hera.v1.resources import Resources

Resources(empty_dir_volume=EmptyDirVolume(mount_path='/vol'))
```

**Comment by flaviuvadan** [comment]
@tachyus-ryan any chance you are interested in contributing an example with the empty directory volume? 🙂
