### ISSUE TITLE
Hera Workflows Don't show on Argo Dashboard

### ISSUE THREAD

**Issue by munachisonwadike** [argoproj-labs/hera-workflows#194]
Hello! 👋🏾👋🏾
I am currently running the hera workflows example code for the [[coin flip](https://github.com/argoproj-labs/hera-workflows/blob/main/examples/coin_flip.py)].
When I run the code, I can't see the workflow on my Argo dashboard (see first screenshot below). However, when I run it a second time, I get an error message saying that the workflow already exists (see second screenshot below). What could be the reason for this apparent contradiction?

![image](https://user-images.githubusercontent.com/22077758/174047522-578d982c-176d-4876-8545-5ffdb4ea54ee.png)

![image](https://user-images.githubusercontent.com/22077758/174047317-08e7f19e-871b-4c52-ba71-b7edcb6d0436.png)

**Comment by munachisonwadike** [comment]
I think it may have something to do with the fact that whenever I submit a workflow, even though I submit to the argo namespace, it shows under the default namespace?


![image](https://user-images.githubusercontent.com/22077758/174050714-4d2237d7-6a12-4853-b1ec-5a54dfadee55.png)

![image](https://user-images.githubusercontent.com/22077758/174050596-cef3d9fb-3ea0-4c12-b505-d46507697851.png)

**Comment by flaviuvadan** [comment]
Hello @munachisonwadike! Thank you for the issue submission! 🙂 This is a consequence of [this line](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/workflow.py#L93) in the workflow. If you set the namespace on the workflow object itself I think everything will be fine. Upon reflection this is an indication that the workflow service namespace interaction with workflow submission is not set up properly. I believe only the workflow objects should have the namespace and the service be agnostic to the namespace. I will add this as a breaking change in a future release. In the mean time, I believe using namespace on workflow objects will solve the problem!
