### ISSUE TITLE
Bash script example?

### ISSUE THREAD

**Issue by Trollgeir** [argoproj-labs/hera-workflows#202]
I've been struggling a bit with the API, and I can't quite seem to figure out how to run a generic script with Hera (independent of python). [Here's an example from the argo workflows running a bash script](https://github.com/argoproj/argo-workflows/blob/master/examples/scripts-bash.yaml).

**Comment by flaviuvadan** [comment]
Hi @Trollgeir 🙂 I believe you're looking for [this example](https://github.com/argoproj-labs/hera-workflows/blob/main/examples/container.py)! A similar example that runs 2 bash commands with Hera:
```python
"""This example showcases how to run a container, rather than a Python, function, as the payload of a task in Hera"""

from hera import Task, Workflow, InputParameter, OutputPathParameter, set_global_host, set_global_token

set_global_host(...)
set_global_token(...)

w = Workflow('container')

g = Task(
    'generate',
    image='alpine:latest',
    command=['sh', '-c'],
    args=["echo $RANDOM > result"],
    outputs=[OutputPathParameter('result', '/result')],
)
c = Task(
    'consume',
    image='alpine:latest',
    command=['sh', '-c'],
    args=["echo result was: {{inputs.parameters.message}}"],
    inputs=[InputParameter('message', g.name, 'result')],
)

g >> c
w.add_tasks(g, c)
w.create()
```
