### ISSUE TITLE
Workflow parameters

### ISSUE THREAD

**Issue by Trollgeir** [argoproj-labs/hera-workflows#206]
Is there a particular reason why [hera workflows do not support parameters](https://argoproj.github.io/argo-workflows/workflow-inputs/)? I would find it very convenient to run:

```
from workflows import some_workflow

some_workflow.create(parameters=[Parameter(name="some_parameter", value="some_value")])
```

This way the workflow support arguments, and its inner working is encapsulated from the user.

Also, I discovered that `GlobalInputParameter` **can never be used**, because it's not possible to add workflow parameters.

**Comment by flaviuvadan** [comment]
No particular reason other than no explicit request for this feature. I think we can incorporate this in 3.6.0!

`GlobalInputParameter` can currently be used when global workflow parameters are set by Argo Events, which was discussed in #138

**Comment by flaviuvadan** [comment]
see #207
