### ISSUE TITLE
Input artifact example fails

### ISSUE THREAD

**Issue by reibuildots** [argoproj-labs/hera-workflows#216]
I'm trying to run "artifact.py" from the examples and receive the following error:
`HTTP response body: {"code":2,"message":"templates.artifact.tasks.consumer templates.consumer.inputs.artifacts.test.from not valid in inputs"}`

Hera version - v3.6
Argo workflow version - v3.3.5

When using Hera version - v3.5 it works

**Comment by flaviuvadan** [comment]
Thank you for reporting this @reibuildots! Going to take a look today
