### ISSUE TITLE
Unable to add volume/secret globally

### ISSUE THREAD

**Issue by bvidovic1** [argoproj-labs/hera-workflows#226]
Based on examples and source I was not able to find how to add emptyDir volume globally, so it is available for all tasks in the workflow. The same goes for the SecretVolume.

I was expecting I could add `Resources` under `Workflow` definition, but that is not the case.
Is there some solution to this or is it missing func?

**Comment by flaviuvadan** [comment]
Hello @bvidovic1! That is currently not supported in Hera but it would certainly be a great addition, especially if your use case would benefit from it! As a temporary workaround, one can add `EmptyDir` and `SecretVolume` to each task under `Resources`, as you alluded to!

**Comment by bvidovic1** [comment]
Hi,

Thanks for the answer.

Yeah, volume definition can be pre-created and added within each task. 
Global secrets and volumes would also be a great addition.

Cheers.

**Comment by giacomov** [comment]
Should we re-open this?

Looks like in v4 we're back to the situation where there is no way of doing this (create a volume globally for a workflow). At least I could not find it by reading the examples and the code of workflow.py.

There was a PR for 3.x that added that capability, but the `volumes` keyword introduced there is not present anymore, and the new way of specifying resources seems to be only defined for Tasks, and not for Workflows.

How can I define a volume shared between all tasks in a workflow with v4?
