### ISSUE TITLE
Use token from ~/.kube/config if no token provided

### ISSUE THREAD

**Issue by rubenvdg** [argoproj-labs/hera-workflows#236]
Currently, in the [Python SDK of argo_workflows](https://github.com/argoproj/argo-workflows/tree/master/sdks/python), I do not need to pass a token explicitly and can just do:
```
import argo_workflows
argo_config = argo_workflows.Configuration(host="....")
api_client = argo_workflows.ApiClient(argo_config)
````
which then uses the token in `~/.kube/config` if I'm not mistaken.

In Hera, I believe this is currently [not possible](https://github.com/argoproj-labs/hera-workflows/blob/f6cf903b8974a76c814d636009b09085dfd3cbf4/src/hera/client.py#L33).

Is this on purpose? It seems to me that using the token from `~/.kube/config` is more convenient and secure than copying/pasting tokens.

**Comment by flaviuvadan** [comment]
Hey @rubenvdg! Thanks for the question 🙂 Does [this example](https://github.com/argoproj-labs/hera-workflows/blob/main/examples/k8s_sa.py) help? It showcases how one can generate a token using a K8S service account. Alternatively, we can definitely look into adding support for that default!

**Comment by rubenvdg** [comment]
Hi @flaviuvadan, thanks for the pointer. It would add an extra dependency though (kubernetes) and also I'm not sure what serviceaccount this pertains to -- since I'll be authenticating with a user account from my local device. 

Probably there are good reasons, but why not just wrap `ArgoApiClient` without adding extra checks on the input -- this seems also appealing from a maintenance perspective. Something like:


```
class Client: 
    def __init__(*args, **kwargs):
        self._client = ArgoApiClient(*args, **kwargs)
...
```

or

```
class Client(ArgoApiClient):
    pass
````

**Comment by flaviuvadan** [comment]
> which then uses the token in ~/.kube/config if I'm not mistaken.
@rubenvdg I looked through the implementation of the SDK (the autogenerated code) and I could not find places that load the kube config file as mentioned. I know Couler does that, though. Any chance you are using Couler for submission of workflows?  

Also, regarding the piece of you showcased:
```python
import argo_workflows
argo_config = argo_workflows.Configuration(host="....")
api_client = argo_workflows.ApiClient(argo_config)
```
Is the configuration token field left to `None` in this case? What is the setup you use for submission of workflows? Do you have a server that hosts Argo remotely or do you perform submissions to localhost:2746?

**Comment by rubenvdg** [comment]
Yes, it's left to `None` (and Argo is hosted remotely). But I wouldn't be able to tell you how the authentication is setup exactly.

**Comment by flaviuvadan** [comment]
> Yes, it's left to None (and Argo is hosted remotely). But I wouldn't be able to tell you how the authentication is setup exactly.

I understand. Can you share whether the host is `localhost:2746` or something else? If the host is `localhost:2746` you can bypass the need for a token because it likely means you are running a port-forward via kubectl, or running Argo on local. If a team in the organization has set up a host different than `localhost:2746` perhaps the detail of whether the `~/.kube/config` is used can be obtained from them? 🤔 I also think [this example](https://github.com/argoproj-labs/hera-workflows/blob/main/examples/k8s_sa.py) can still work if you have access to, say, the `argo` service account (if there is one set up in the cluster)

**Comment by flaviuvadan** [comment]
Closing this for now but feel free to reopen if you can share some examples you think may be helpful for diagnosing the use of Hera in this scenario!
