### ISSUE TITLE
Support for managing k8s resource from workflow

### ISSUE THREAD

**Issue by jalkjaer** [argoproj-labs/hera-workflows#248]
It seems there is currently no support for managing k8s resources as described in https://argoproj.github.io/argo-workflows/walk-through/kubernetes-resources/
Is that so or have I overlooked something?

**Comment by flaviuvadan** [comment]
Hi @jalkjaer! Would [this PR](https://github.com/argoproj-labs/hera-workflows/pull/214) solve the use case? If so, the plan is to release it as part of v4, soon!

**Comment by flaviuvadan** [comment]
V4 releaseD support for running arbitrary K8S manifests! Check it out on 4.0.0rc1! 🙂
