### ISSUE TITLE
How to set custom args for dynamic fanout based on output of last step

### ISSUE THREAD

**Issue by lamhoangtung** [argoproj-labs/hera-workflows#250]
Hi. Thanks for the amazing library.

I'm having a use case where each task are just container task. Assuming we have this first generate task, that pump out to stdout some JSON output like this:
```
["a", "b", "c"]
```
And then dynamic fanout create 3 task to run in parallel. Since all task are just container task, a way to parse in output from the last task can be via cli arguments, so each dynamically created task should have this kind of arg
```
--name a # for sub task 1
--name b # for sub task 2
--name c # for sub task 3
```

How can I do this with hera-workflows ? Thanks!

**Comment by flaviuvadan** [comment]
Hello again @lamhoangtung! Thanks for the question :) for containers I believe you might have to do the parameter inference yourself. Something like `--name {{inputs.parameters.value}}` might work? Perhaps [this](https://github.com/argoproj/argo-workflows/discussions/5740) might help!

**Comment by lamhoangtung** [comment]
Thanks for helping @flaviuvadan. That worked ! Here is an working example script:
```python
from hera import (
    InputFrom,
    MultiInput,
    OutputPathParameter,
    Task,
    Workflow,
    WorkflowService,
)

def generate():
    import json
    import sys

    # this can be anything! e.g fetch from some API, then in parallel process all entities; chunk database records
    # and process them in parallel, etc.
    json.dump([{"value": i} for i in range(10)], sys.stdout)


def fanout(value: int):
    print(f"Received value: {value}!")
    with open("/tmp/number", "w") as f:
        f.write(str(value))


with Workflow(
    "dynamic-fanout-arg",
    service=WorkflowService(host='https://localhost:2746', token=""),
    namespace="argo"
) as w:
    generate_task = Task("generate", generate)
    fanout_task = Task(
        "fanout",
        input_from=InputFrom("generate", ["value"]),
        image="alpine:latest",
        command=["echo"],
        args=["{{inputs.parameters.value}}"],
    )

    generate_task >> fanout_task

w.create()
```
![image](https://user-images.githubusercontent.com/26834698/189101739-2cfc1968-9bb0-4551-a84c-6dedf710178c.png)

**Comment by flaviuvadan** [comment]
@lamhoangtung would you like to open a PR with the example explaining fanout + containers? 🙂

**Comment by lamhoangtung** [comment]
Sure I just did. Can you take a look @flaviuvadan ?
