### ISSUE TITLE
Blog post

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/hera-workflows#26]
I think someone should write blog post about this.

**Comment by flaviuvadan** [comment]
> I think someone should write blog post about this.

I am working on one for @dynotx's website. Would one work for [Argo ](https://blog.argoproj.io/) as well?

**Comment by flaviuvadan** [comment]
First one: https://www.dynotx.com/hera-the-missing-argo-workflows-python-sdk/

**Comment by alexec** [comment]
Tweeted!

**Comment by flaviuvadan** [comment]
Hera was presented in several blogs: the DynoTx one above and also the v3.3 release one!
