### ISSUE TITLE
Is Python 3.11 supported? - possible accidental revert

### ISSUE THREAD

**Issue by nikhiljha** [argoproj-labs/hera-workflows#276]
I noticed this commit https://github.com/argoproj-labs/hera-workflows/commit/c93b1a0635177812de5e87cce30b47c67f39e1fb modified `pyproject.toml` to enforce a constraint that `python < 3.11`, which this commit previously removed:https://github.com/argoproj-labs/hera-workflows/commit/f6cf903b8974a76c814d636009b09085dfd3cbf4. It doesn't seem like there's any reason to explicitly disallow Python 3.11. Was that intentional, or were mistakes made while merging branches? 😄

Right now, poetry complains when I try to depend on `hera-workflows`...

> The current project's Python requirement (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
>  - hera-workflows requires Python >=3.7,<3.11, so it will not be satisfied for Python >=3.11,<4.0

**Comment by Trollgeir** [comment]
Nice find!
I'm fairly sure this was accidental. @flaviuvadan ?

**Comment by flaviuvadan** [comment]
That was likely a bad merge conflict resolution, apologies 😕 we can likely remove it!
