### ISSUE TITLE
Ability to label workflows and tasks 

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/hera-workflows#29]

**Comment by bobh66** [comment]
@flaviuvadan Is this as simple as adding a labels attribute to the Task, Workflow and CronWorkflow objects and passing it through to the V1ObjectMeta?  I'd be happy to take this as I could really use label support for my application.

**Comment by flaviuvadan** [comment]
@bobh66 that is correct! The way I think about this is presenting a simple interface to users so they can set an arbitrary mapping `labels: Dict[str, str] = {}` on a workflow object, which then propagates the labels to the tasks! I'd be excited for your contribution 🙂  and thank you for the other PRs you have submitted thus far!

**Comment by bobh66** [comment]
Great - I need this functionality so I'll push a new PR with these changes.  Should it also support annotations?  That's the only other metadata attribute that looks like it might be useful at this stage.

**Comment by dmerrick** [comment]
I think it'd be fine if your PR only supported `labels` for now. The annotation support could come in a future PR (and use your PR as an example)

**Comment by bobh66** [comment]
I don't see a way to label Tasks as they don't have V1ObjectMeta objects.  It appears that we can support labels for Workflows, CronWorkflows and Volumes (the PVC gets the label).

**Comment by flaviuvadan** [comment]
> I don't see a way to label Tasks as they don't have V1ObjectMeta objects. It appears that we can support labels for Workflows, CronWorkflows and Volumes (the PVC gets the label).

The `Task` template has a field called metadata that takes a `V1alpha1Metadata`! 🙂  That object has these OpenAPI types on it:
```
openapi_types = {
    'annotations': 'dict(str, str)',
    'labels': 'dict(str, str)'
}
```

Perhaps we can instantiate an empty `V1alpha1Metadata` on the `Task` and then set the `labels` on it through the `Workflow`/`CronWorkflow`?

**Comment by flaviuvadan** [comment]
> I think it'd be fine if your PR only supported `labels` for now. The annotation support could come in a future PR (and use your PR as an example)

I will echo what @dmerrick mentioned here 🙂  Let's release these in separate PRs so we (1) keep PRs small (easy to review and add tests for), and (2) incrementally add features (opportunity to write an Issue to for a well-defined use case)!

**Comment by bobh66** [comment]
OK - I'll work on this as soon as the timezone patch is merged so I don't have a merge conflict with the version file.

Do we want each Task to inherit the labels of the workflow?   Or should each Task be able to have it's own labels?  I assume the latter.  Thanks

**Comment by flaviuvadan** [comment]
> Do we want each Task to inherit the labels of the workflow? Or should each Task be able to have it's own labels? I assume the latter. Thanks

I think the default behavior of Argo is if a workflow specified labels, they are applied to all tasks and tasks have the ability to overwrite those labels. So, I agree with what you mentioned - the latter option seems like the way to go! 🙂
