### ISSUE TITLE
Support for argo workflows custom metrics to report about workflow failures 

### ISSUE THREAD

**Issue by abhishektvz** [argoproj-labs/hera-workflows#298]
Hi, we had been using argo wf custom prometheus metrics to manage alerts for failing workflows, 

https://argoproj.github.io/argo-workflows/metrics/
https://github.com/argoproj/argo-workflows/blob/master/examples/custom-metrics.yaml

would it be possible to make this a part of the upcoming release ?

**Comment by flaviuvadan** [comment]
Yes, absolutely :) @Trollgeir and I would like to release v4 soon (tomorrow probably) and we can either (1) include it in that or (2) add it with 4.1 quickly after!
