### ISSUE TITLE
Workflow.get_name() returns constant string.

### ISSUE THREAD

**Issue by timothyngo** [argoproj-labs/hera-workflows#314]
Hi, I noticed that Workflow.get_name always returns "{{workflow.name}}". Was the code intended to return generated_name or name?

**Comment by flaviuvadan** [comment]
Hi @timothyngo! Thanks for the question. The purpose of `get_name()` is to help users access the _resolved_ workflow name. This refers to the Argo Workflows variable that represents the workflow name. Here's an example:
```python
from hera import Task, Workflow

def p(name: str):
    print(name)


with Workflow('my-workflow') as w:
    Task('p', p, with_param=[w.get_name()])
w.create()
```
![Screen Shot 2022-10-12 at 9 02 37 PM](https://user-images.githubusercontent.com/18152652/195489353-56bb0d3b-7a22-4aa3-92d9-5386dcd1f63b.png)

**Comment by timothyngo** [comment]
Okay, thanks! The example clarified a lot!
