### ISSUE TITLE
Question: Documentation?

### ISSUE THREAD

**Issue by heavelock** [argoproj-labs/hera-workflows#315]
Hey! 

Does that package have any more documentation than just the README file?

Cheers,
Damian

**Comment by flaviuvadan** [comment]
Hey Damian! Thanks for the question :) Is there specific documentation type that you are asking about? Like a website, perhaps? Or, more docstring within Hera's code?

**Comment by heavelock** [comment]
Website with more than a comparison example, some use cases, potentially a tutorial, documentation of the API in form of collected docstrings. 

I wanted to evaluate usage of hera in my team but without a centralized documentation it will be quite hard to convince anyone to use it.

**Comment by flaviuvadan** [comment]
Thank you for the feedback @heavelock :) I chatted with @Trollgeir about this and we'll look into spinning up a ReadTheDocs page for Hera!

**Comment by heavelock** [comment]
That's great to hear! Looking forward for that!

Cheers,
Damian

**Comment by flaviuvadan** [comment]
The first docs series is available at https://hera-workflows.readthedocs.io/en/latest/!
