### ISSUE TITLE
Better support for GitOps & generating YAML

### ISSUE THREAD

**Issue by valorl** [argoproj-labs/hera-workflows#316]
Hi, 

For e.g. a CronWorkflow, it's possible, and quite useful to manage it with GitOps. However, it doesn't seem like Hera's API supports this very well. The API assumes imperative submission of resources with the `create()` method. It would be great to be able to simply generate a fully valid Kubernetes manifest instead of directly talking to the API.

I've tried using `build()` instead of `create()` and serializing it myself with pyyaml, however that payload is not fully valid, e.g.:
- props use snake_case instead of camelCase
- The `apiVersion` and `kind` fields are missing

Other than "patching" this payload myself, are there any alternative APIs in Hera and/or the Argo Python SDK that could help me get a valid Kubernetes manifest out of a `hera.cron_workflow.CronWorkflow` instance ? If not, consider this a feature request.

**Comment by Trollgeir** [comment]
We've considered making this a feature (we've had similar request). However, I was also a bit worried that implementing it would make consumers stray a way from the intended path of applying these CronWorkflows/Templates directly with hera -> argo API. 

I'm also curious if you'd be willing to share how you've set up your CI/CD. Do you intend of resolving the YML-file locally before committing it to a repository, where the CI/CD picks up on it with kubernetes? Or do one of your steps run the python code generating the yml file, and you want to forward it to kubernetes? If it's the latter of these, what holds you back from doing `.create()` at the end?

**Comment by valorl** [comment]
We use GitOps and FluxCD heavily to be able to spin clusters up and down without having to re-run CI and re-apply things.
> Do you intend of resolving the YML-file locally before committing it to a repository, where the CI/CD picks up on it with kubernetes? Or do one of your steps run the python code generating the yml file, and you want to forward it to kubernetes?

It could be either of these approaches. For our more standard K8S resources, we actually generate them in CI and then ship them to a Git repo. Then whenever we spin up a cluster, it auto-bootstraps, installing Flux pointed at that repo, and applying (continuously) all the manifests in it. 

> If it's the latter of these, what holds you back from doing `.create()` at the end?

Doing a `.create()` is basically the equivalent of doing a `kubectl apply` in your CI. The main issue with this is that it's hard to guarantee that the state of the manifest remains as it was at the time of the create/apply. If you instead put the manifest in a Git repo and use a GitOps operator like Flux or ArgoCD, it will always be reconciled back to the state stored in Git. And as I mentioned, it also allows us to bootstrap new clusters quickly and robustly.

> The API assumes imperative submission of resources with the create() method.

I was just pointing out basically what you said as well:

> the intended path of applying these CronWorkflows/Templates directly with hera -> argo API

Using the Argo API instead of raw K8S is great for the additional validation etc, and it makes sense for applying Workflows since those are more ephemeral, you basically just need the spec to kick-off a computation once. But CronWorkflows and (Cluster)WorkflowTemplates you want to make sure they stay as declared for a long time, which is something that these GitOps operators are great at.

And also more in general, I think raw K8S manifests/objects are a powerful common denominator for the ecosystem and I always appreciate when tools/SDKs allow you to generate the manifests (e.g. `helm template` instead of `helm install`) cause it often allows me to reuse my existing tech/process.

**Comment by flaviuvadan** [comment]
@valorl, @Trollgeir and I had a chat about this and we decided to introduce YAML manifest generation to Hera. We're going to attempt a release of that this week sometime. The PR will address the two concerns your brought up:
- props use snake_case instead of camelCase
- apiVersion and kind fields are missing
and will introduce a `to_yaml` on the workflow objects (workflow, cron workflow, workflow template). Going to CC you on the PR!

**Comment by flaviuvadan** [comment]
@valorl please see https://github.com/argoproj-labs/hera-workflows/pull/327 whenever you have the chance to!
