### ISSUE TITLE
Tasks with params cannot generate fanouts

### ISSUE THREAD

**Issue by JacobHayes** [argoproj-labs/hera-workflows#318]
Fanout generating tasks, like:
https://github.com/argoproj-labs/hera-workflows/blob/c93b1a0635177812de5e87cce30b47c67f39e1fb/examples/dynamic_fanout.py#L9-L15

work when used like this:

https://github.com/argoproj-labs/hera-workflows/blob/c93b1a0635177812de5e87cce30b47c67f39e1fb/examples/dynamic_fanout.py#L24-L25

However, if you add a parameter to `generate`, then the `consume` step no longer acts as a fanout with each pod getting 1 list element, but instead causes a single `consume` pod receiving the entire list.

This behavior changed in Hera 4 (the syntax in 3 used `input_from` in the `consume` task, but I'm not sure that's exactly the relevant part).

---

For example, this script will generate two workflows, but only `generate_no_params` causes a fanout (make sure to adjust to add host/tokens as needed):
```python
from uuid import uuid4

from hera import Task, Workflow

def generate_no_param():
    import json
    import sys

    json.dump(list(range(10)), sys.stdout)

def generate_param(something: str):
    import json
    import sys

    json.dump(list(range(10)), sys.stdout)

def consume(task_metadata_file: str) -> None:
    print(f"Received value: {task_metadata_file}!")

with Workflow(f"dynamic-fanout-without-params-{uuid4().hex[:8]}") as w:
    generate_task = Task("generate", generate_no_param)
    consume_task = Task("consume", consume, with_param=generate_task.get_result())

    generate_task >> consume_task
w.create()

with Workflow(f"dynamic-fanout-with-params-{uuid4().hex[:8]}") as w:
    generate_task = Task("generate", generate_param, with_param=[{"something": "😛"}])
    consume_task = Task("consume", consume, with_param=generate_task.get_result())

    generate_task >> consume_task
w.create()
```
The `generate*` tasks and outputs look reasonable:
```python
>>> generate_no_param_task = Task("generate", generate_no_param)
>>> generate_param_task = Task("generate", generate_param, with_param=[{"something": "😛"}])
>>> generate_no_param_task
Task(inputs=[], outputs=[])
>>> generate_param_task
Task(inputs=[<hera.parameter.Parameter object at 0x10f4cb910>], outputs=[])
>>> generate_no_param_task.get_result()
'{{tasks.generate.outputs.result}}'
>>> generate_param_task.get_result()
'{{tasks.generate.outputs.result}}'
```
so there must be some other internal state that is off (is there any logic on the _subtask_ that inspects the parent task to determine whether to fanout?).

**Comment by JacobHayes** [comment]
<img width="994" alt="Screen Shot 2022-10-19 at 18 05 10" src="https://user-images.githubusercontent.com/2555532/196813586-cc06a9b5-ecb0-4516-a944-46e3df8f0d1a.png">
<img width="1390" alt="Screen Shot 2022-10-19 at 18 05 17" src="https://user-images.githubusercontent.com/2555532/196813589-82b00797-0f53-463e-b34a-a39d4f7062fd.png">

**Comment by Trollgeir** [comment]
This issue occurs because `with_param` generates a list of objects - and in this case the result will be `[[0,1,2,3..]]` since we're dealing with a single element ( `[{"something":  "😛"}]` ). When you're chaining it to another task with `with_param`, it tries to map every element in the outer list to each task, thus ending up with `[0,1,2,3..]` to a single task.

It's more clear what happens if you'd for example set the `generate`'s `with_param=[{"something": "A"}, {"something": "B"}]`

You can solve your issue by setting `inputs=[Parameter("something",  "😛")])` in the `generate` task instead of `with_param`.

**Comment by Trollgeir** [comment]
..and instead of using the uuid, you can instead just do:
`with Workflow("dynamic-fanout-with-params-", generate_name=True) as w:`

**Comment by JacobHayes** [comment]
Thanks @Trollgeir, that fixed the issue for us! Is `inputs=[Parameter(...)]` the simplest interface? It'd be nice to have a high level interface for non-fanout parameters too that doesn't require creating `Parameter` objects (maybe I'm just spoiled from `with_param` 😁).

I'll close this since the OP is covered.

**Comment by Trollgeir** [comment]
If anything we might be permissive and allow `Dict` for `inputs`, transforming it to a `Parameter` under the hood.
