### ISSUE TITLE
Workflow_template_ref  issue

### ISSUE THREAD

**Issue by kavitajoshi14** [argoproj-labs/hera-workflows#319]
I have created a WorkflowTemplate, but the tasks are coming under templates not under tasks.
![image](https://user-images.githubusercontent.com/98482866/196863722-44fe9fc1-d308-4f9d-a058-4e3dcc621cb9.png)
that is why i am having issue while creating the workflow_template_ref.
![image](https://user-images.githubusercontent.com/98482866/196863882-b765508c-e95d-4ed9-9def-e475e8dd71b1.png)

**Comment by abhishektvz** [comment]
To add some context to it, @kavitajoshi14 just moved a workflow to a workflowtemplate, but suddenly the tasks are not showing up,
we are definitely defining the Task pipeline using the `>>` operator but we do not see the tasks listed in the template,
this same definition was working fine when we were running it directly as a workflow

**Comment by Trollgeir** [comment]
The Workflow-object always holds a DAG with a set of tasks referencing templates. When you convert it to a WorkflowTemplate, the DAG is discarded. WorkflowTemplates is only supposed to hold a set of templates, not how they're stitched together.

However, if the task itself is a DAG, it should be contained in the template. See [this](https://github.com/argoproj-labs/hera-workflows/blob/main/examples/parallel_dag.py) example for inspiration!

**Comment by Trollgeir** [comment]
Looking at the examples we currently have with `WorkflowTemplate` and referencing them, I see that our examples are outdated, and I also discovered a bug in the code which prevents any DAGs from being created for templates.

I'll put up a PR in the coming days and we'll bump hera to the next version with new examples.

Thanks a lot for the issue!

**Comment by Trollgeir** [comment]
https://github.com/argoproj-labs/hera-workflows/pull/320

**Comment by Trollgeir** [comment]
Will likely have a release by this week. (https://github.com/argoproj-labs/hera-workflows/issues/316#issuecomment-1289114900)
