### ISSUE TITLE
Community channel

### ISSUE THREAD

**Issue by abhishektvz** [argoproj-labs/hera-workflows#326]
Hi guys, I see Hera workflows is gaining momentum on the tech side, would it make sense to have a discord server up and running where people can converse about Hera workflows ?

We at TechVZero would be happy to take initiative and create a community channel and we can let it grow organically according to how the community wants

**Comment by Trollgeir** [comment]
That's great to hear!

We're currently in the hera channel in cloud native slack, [here](https://cloud-native.slack.com/archives/C03NRMD9KPY)

**Comment by flaviuvadan** [comment]
@abhishektvz does TechVZero use Slack and did you have the chance to join the #hera channel? :)

**Comment by flaviuvadan** [comment]
Closing for now as the CNCF #hera channel serves as the main point of community interactions for now!
