### ISSUE TITLE
Question about external dependencies in workflows defined with hera 

### ISSUE THREAD

**Issue by dbragdon1** [argoproj-labs/hera-workflows#330]
Hello, I am attempting to write a workflow that requires external dependencies. For example, if I have a simple step like this that imports pandas as a dependency, 

```python
def hello():
    import pandas as pd

    print("Hello")


service = WorkflowService(
    host=host, token=auth_token, namespace="argo-production"
)
with Workflow(
    "hello-hera",
    service=service,
) as w:
    Task("t", hello)

w.create()
```

how would tell I hera that this is a dependency required by my workflow? Is this possible at all? Or do I need to use a docker image with a python environment already loaded into it? 

Metaflow [tries to solve this](https://docs.metaflow.org/scaling/dependencies), but it's still not ideal as the only supported environment is conda.

**Comment by abhishektvz** [comment]
@dbragdon1 we have been using external dependencies by specifying a custom docker image in the `image` parameter for the task, since even for a python function, it just uses a default `python` docker image

**Comment by Trollgeir** [comment]
The user has to supply or refer to an image with the environment. For pandas, there are readily available public images with this package included.

But even if this _would_ be a feature, would you really want your argo-jobs to have to install the environment every time you triggered a job? This would be a waste of compute and time.

**Comment by flaviuvadan** [comment]
@dbragdon1, did the above discussion help with the understanding of why the scenario you describe needs a custom container? Is there anything in Hera that could have made this clearer, perhaps?

**Comment by dbragdon1** [comment]
> @dbragdon1, did the above discussion help with the understanding of why the scenario you describe needs a custom container? Is there anything in Hera that could have made this clearer, perhaps?

Thanks for checking in on this issue. Like I said, the type of local dependency loading that I'm looking for might be out of the scope of what hera workflows is trying to accomplish. Using an external image seems like the correct way to go as of now. Thanks again.

**Comment by dbragdon1** [comment]
> The user has to supply or refer to an image with the environment. For pandas, there are readily available public images with this package included.
> 
> But even if this _would_ be a feature, would you really want your argo-jobs to have to install the environment every time you triggered a job? This would be a waste of compute and time.

Right, installing all of the packages again at every step would be a waste of time. I was more referring to a method of persisting the packages in their installed form inside of a cloud service such as s3. This could mean copying the virtual environment, in the case of package managers like poetry or venv, or simply copying the contents of the `__pypackages__` directory to s3. These packages are then mounted into the relevant container as a volume during a given step, which I believe would be much faster than reinstalling them every time. If hera workflows could support this and automatically cache a project's dependencies in s3, then it would allow for a user to create a workflow with external dependencies without needing to create a separate docker image.

**Comment by Trollgeir** [comment]
I would not endorse a dev-ops system that's based on caching virtual environments with mapping to python base images (not all venvs would be compatible with all images). If you're planning on deploying something to production at some point, I'd -heavily- recommend having your own container registry. 

I understand the appeal for the system you're proposing if you're just testing if hera/argo would be the right tool for the job, and you've not yet setup any cloud environment. But if you're already at a point in which you have access to write to a cloud bucket, I'd imagine you're not very far away from creating a container registry either.

**Comment by flaviuvadan** [comment]
Going to close this issue as it is not something that will be supported in the near future (next ~6 months). However, it will be kept in the ideas stash as a potential extension of Hera! If this ends up being supported by Hera we will reference back to this original issue
