### ISSUE TITLE
Suggestion: set up a gitpod.io workspace

### ISSUE THREAD

**Issue by elliotgunton** [argoproj-labs/hera-workflows#333]
Credit to @samj1912 for suggesting - the project could utilise gitpod.io to host a ready-to-go workspace which would help us when contributing - it provides an externally-hosted dev environment. Including a `.gitpod.yml` would also although pre-builds and start up commands e.g. https://github.com/samj1912/buildpacks-venom-executor/blob/main/.gitpod.yml

**Comment by samj1912** [comment]
Other related gitpod-ified repos for inspiration - 

- https://github.com/buildpacks/pack/blob/main/.gitpod.yml
- https://github.com/PyCQA/pydocstyle/blob/master/.gitpod.yml
- https://github.com/prometheus/prometheus/blob/main/.gitpod.yml
- https://github.com/babel/babel/blob/main/.gitpod.yml
- https://github.com/SeleniumHQ/selenium/blob/trunk/.gitpod.yml
- https://github.com/apache/airflow/blob/main/.gitpod.yml
- https://github.com/jenkinsci/jenkins/blob/master/.gitpod.yml
