### ISSUE TITLE
Question about Parameter class converting values to string :question: 

### ISSUE THREAD

**Issue by hera-user** [argoproj-labs/hera-workflows#341]
Hello,

In a recent MR the Parameter class was changed such that it [converts the value it gets automatically to string](https://github.com/argoproj-labs/hera-workflows/blob/1a6f6f6a5adb20c0b566615bda86723b6febab14/src/hera/parameter.py#L39).
Why does that happen? I tried passing a boolean parameter and it creates a logic error for me as passing it as a condition to an if will be redundant.
Is there another way to pass non string parameters without artifacts?

Thank you

**Comment by samj1912** [comment]
This is because the upstream argo workflows CR expects it to be a string. See https://argoproj.github.io/argo-workflows/fields/#parameter

<img width="758" alt="image" src="https://user-images.githubusercontent.com/16130816/198887819-ce90a50b-65a7-412e-92ac-b442363a6498.png">

**Comment by flaviuvadan** [comment]
@hera-user, did you find the documentation helpful? Can we close this issue, perhaps?

**Comment by flaviuvadan** [comment]
Closing as @samj1912 answered the question and lack of activity. Of course, feel free to open if things are unclear still!

**Comment by flaviuvadan** [comment]
In retrospect, I realized we should do a `json.dump` on the input `value` the same way we do with the usage of `with_param` so that the `json.loads` in the task will reconstruct the boolean value, will PR this
