### ISSUE TITLE
Support unset parameter values for workflows

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/hera-workflows#346]
Argo Workflow YAML files can be created with parameters with unset values. These values are set upon workflow creation via the Argo CLI, which sets the parameter values. Users would like to create such YAML files via Hera and then use the Argo CLI to parameterize the workflow. Hera workflow parameters currently require values to be set but they should not given the way Argo Workflows support parameters without values

**Comment by elliotgunton** [comment]
+1 I found this problem today when trying to re-create yaml WorkflowTemplates in Hera. Will also add a note to https://github.com/argoproj-labs/hera-workflows/issues/345 but wanted to raise here as the other use case from 
>create such YAML files via Hera and then use the Argo CLI to parameterize the workflow

would be using a `WorkflowTemplate` with parameters that don't have defaults, in which case using the template in a `TemplateRef` without the parameter present in the `Task`'s `inputs` fails the workflow when linting/creating.

**Comment by dbragdon1** [comment]
+1 also ran into this issue today. I have a lot of templates that I reuse and inherit in downstream workflows, where each workflow uses the same template but with different parameters. Would really appreciate this being implemented.
