### ISSUE TITLE
Add support for suspend + inputs 

### ISSUE THREAD

**Issue by samj1912** [argoproj-labs/hera-workflows#347]
Argo 3.4 allows intermediate workflow parameters. See https://argoproj.github.io/argo-workflows/intermediate-inputs/

We should add support for the suspend template. https://argoproj.github.io/argo-workflows/workflow-concepts/#suspend

**Comment by flaviuvadan** [comment]
I did not even see the 3.4 release notes 🤯 this would be very cool. Thank you @samj1912! Added the enhancement and will add it in the coming weeks on the path to 4.3

**Comment by Trollgeir** [comment]
Does this object even exist in the argo python SDK (it's outdated and all). We might be able to hack it in creating our own objects. Creating our own SDK should make this easier.

**Comment by samj1912** [comment]
Suspend template only takes in duration right now https://github.com/argoproj/argo-workflows/blob/master/sdks/python/client/argo_workflows/model/io_argoproj_workflow_v1alpha1_suspend_template.py

The main object that supports the is the valueFrom object which should support `supplied` https://argoproj.github.io/argo-workflows/fields/#valuefrom which is present https://github.com/argoproj/argo-workflows/blob/ec94001a032390c2802fb22ffff0e78e46607b77/sdks/python/client/argo_workflows/model/io_argoproj_workflow_v1alpha1_value_from.py#L98
