### ISSUE TITLE
Add support for resource template type

### ISSUE THREAD

**Issue by samj1912** [argoproj-labs/hera-workflows#348]
See https://argoproj.github.io/argo-workflows/workflow-concepts/#resource

**Comment by flaviuvadan** [comment]
Thanks for the idea @samj1912 🚀 I assume you saw the [resource template](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/resource_template.py) object in Hera and this suggestion is oriented towards refining the [manifest](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/resource_template.py#L37)?

**Comment by samj1912** [comment]
Ah! I had not seen that, thanks for the link! I should have searched more before creating the issue. Should we instead create an issue to document an example using the above template?

**Comment by flaviuvadan** [comment]
That SGTM!
