### ISSUE TITLE
hera name validation is too strict 

### ISSUE THREAD

**Issue by samj1912** [argoproj-labs/hera-workflows#353]
Argo allows workflow template names to contain `.`.

Hera however prohibits this. Hera validation logic should be updated to match the restrictions at https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names

**Comment by Trollgeir** [comment]
We decided to postpone this and instead keep the same validation logic for the workflow and template names for the initial implementation, and eventually branch it off into separate validations.

We're also looking into shifting all the models over to pydantic at some point which could utilize the native pydantic validation system and autogenerate all the models based on Argo's OpenAPI spec. What would be amazing would be if Argo's OpenAPI spec with constrained name fields could also be decorated with a [pattern](https://swagger.io/docs/specification/data-models/data-types/#pattern) (regex). This should then also be propagated to our autogenerated pydantic models.

 CC @alexec
