### ISSUE TITLE
`to_yaml` and namespaces

### ISSUE THREAD

**Issue by yjabri** [argoproj-labs/hera-workflows#354]
This project looks really great and I'm interested in trying it out. My plan is to try to incrementally add it to my project and I was planning on using `w.to_yaml(...)` after creating a workflow `w`. Unfortunately I can't seem to add a namespace to my workflow. According to https://github.com/argoproj-labs/hera-workflows/pull/219 this is by design. Are there any work arounds to support namespaces and `to_yaml`?

Thanks!

**Comment by Trollgeir** [comment]
How are you planning on pushing the workflow to the cluster? By using the argo-cli you can specify the namespace.

**Comment by yjabri** [comment]
I'm in the process of making the case for Argo Workflows to my team so we just use a bare bones `kubectl apply -f` as it's one less thing to install.

After checking out the code and seeing `.to_yaml` is just a thin wrapper around `.to_dict` I was able to write my own utility that specifies a namespace and outputs yaml. I'll go ahead and close this issue.

**Comment by Trollgeir** [comment]
You can also specify the namespace with `kubectl` though, like
`kubectl apply -f worflow.yaml --namespace=test`
