### ISSUE TITLE
Using a WorkflowTemplate in a context manager widens the type (mypy)

### ISSUE THREAD

**Issue by elliotgunton** [argoproj-labs/hera-workflows#357]
When using a WorkflowTemplate like so (minimal bug repro):

```py
def get_workflow_template() -> WorkflowTemplate:
    with WorkflowTemplate(name="my-template") as wt:
        pass

    return wt  # error line
```

We get the mypy error:
```
/workflows/workflow_template.py:5: error: Incompatible return value type (got "Workflow", expected "WorkflowTemplate")  [return-value]
```

This is because the `WorkflowTemplate` class inherits the `__enter__` function, which returns a `Workflow` type, thus widening the type of `wt` in the code above to a `Workflow`, despite it being a `WorkflowTemplate` the whole time. A current workaround is

```py
from typing import cast
# ...
    return cast(WorkflowTemplate, wt)
```

Proposed solution is to use a "self" type to allow the class and its subclasses to pass type checks which can be achieved pre python 3.11 through a `TypeVar`, and from 3.11 using `from typing import Self`. So in `workflow.py` we could add/change:

```py
from typing import TypeVar

WorkflowType = TypeVar("WorkflowType", bound="Workflow")

class Workflow:
    # ...
    def __enter__(self) -> WorkflowType:
        # ...
```

However, having tried this, it seems I need to explicitly annotate the type of the context manager which is annoying...
```py
def get_workflow_template() -> WorkflowTemplate:
    with WorkflowTemplate(name="my-template") as wt:  # type:WorkflowTemplate
        pass

    return wt  # no mypy errors
```

**Comment by flaviuvadan** [comment]
Awesome suggestion @samj1912! 🚀
