### ISSUE TITLE
how can we use imagePullSecrets in hera 

### ISSUE THREAD

**Issue by kavitajoshi14** [argoproj-labs/hera-workflows#372]
we are going to use our private docker repository to pull the images for that we need to add the imagePullSecrets in the workflow templates

**Comment by flaviuvadan** [comment]
Will add it soon in 4.3!

**Comment by flaviuvadan** [comment]
Hi @kavitajoshi14 I just verified that we actually have this on [workflows](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/workflow.py#L116)!
