### ISSUE TITLE
Possible regression: no workspace volumes in v4

### ISSUE THREAD

**Issue by giacomov** [argoproj-labs/hera-workflows#373]
Related to #226 :

Looks like in v4 we're back to the situation where there is no way of creating a volume globally for a workflow. At least I could not find it by reading the examples and the code of workflow.py.

There was a PR for 3.x that added that capability, but the volumes keyword introduced there is not present anymore, and the new way of specifying resources seems to be only defined for Tasks, and not for Workflows.

How can I define a volume shared between all tasks in a workflow with v4?

**Comment by flaviuvadan** [comment]
Hey @giacomov! Hera 5.0.0rc1 was just released. Hera now has feature parity with Argo Workflows! So, you will find [volumes on workflows](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/workflows/workflow.py#L125) again :)
