### ISSUE TITLE
Feature request: support for archivelog

### ISSUE THREAD

**Issue by ipl31** [argoproj-labs/hera-workflows#375]
It appears argo supports setting archive log on the Workflow spec and template. It would be nice to have this supported in hera.

https://argoproj.github.io/argo-workflows/configure-archive-logs/

**Comment by flaviuvadan** [comment]
@ipl31 Hera 5.0.0rc1 was just released! Hera has now feature parity with Argo Workflows, which includes [archive logs on workflow](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/workflows/workflow.py#L89) and [on templates](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/workflows/_mixins.py#L250)! Going to close this for now. Feel free to reopen it if you'd like to discuss this further! :)
