### ISSUE TITLE
Garbage Collection

### ISSUE THREAD

**Issue by danielc103** [argoproj-labs/hera-workflows#382]
In Argo Workflows v3.4 there are a couple of garbage collections features I can't find in `hera` .

`podGC` - which removes the pods after workflow completion

https://argoproj.github.io/argo-workflows/fields/#podgc

`artifactGC` - which removes artifacts after workflow completion

https://argoproj.github.io/argo-workflows/walk-through/artifacts/#artifact-garbage-collection

Is there any plans to support these features directly or is there some way we can achieve these same effects with the current source code?

**Comment by flaviuvadan** [comment]
Hi @danielc103! Yes, absolutely! Hera is ramping up for generating all of the Argo models using Pydantic + OpenAPI specs. This will bring Hera to feature parity with Argo. We're likely going to generate the models using the latest version of Argo. A PR should be available in the next 2 weeks or so

**Comment by danielc103** [comment]
@flaviuvadan excellent! Excited about that MR. Thank you for the response.

**Comment by flaviuvadan** [comment]
Will CC you! :)
