### ISSUE TITLE
Multitask Dag

### ISSUE THREAD

**Issue by alejoGT1202** [argoproj-labs/hera-workflows#386]
Hi,

I was wondering if there is an example of how to create complex workflows.

I would like to create a workflow similar to this one, but I haven\t figured out how to specify the steps when I'm creating the workflow.

Thanks for the help, 

![image](https://user-images.githubusercontent.com/99010562/208092848-a08de1c5-e882-4145-99ea-e07fec90cc5e.png)

**Comment by flaviuvadan** [comment]
Hi @alejoGT1202! [This example](https://github.com/argoproj-labs/hera-workflows/blob/main/examples/parallel_dag.py) might help, perhaps? Something like the above can be achieved with (pseudocode):
```python
with Workflow(...) as w:
    with DAG(...) as d1:                # make a DAG to run inside the workflow
        Task(...) >> Task(...)          # this is a DAG for the inner DAG in the screenshot
    Task(...)                                  # this is the single task that's running in the screenshot
    Task(..., dag=d1)                   # this actually makes the DAG runs in the screenshot, can even fan out using `with_param`
```

**Comment by flaviuvadan** [comment]
@alejoGT1202 did the above example help? If so, should we close this issue?

**Comment by alejoGT1202** [comment]
Yes it helped. Thanks.
