### ISSUE TITLE
Clearer documentation about using `--auth-mode=server` or `--auth-mode=client` 

### ISSUE THREAD

**Issue by BnJam** [argoproj-labs/hera-workflows#394]
The README line pointing at [Argo Workflows](https://github.com/argoproj-labs/hera-workflows/blob/4efddc85bfce62455db758f4be47e3acc0342b4f/README.md?plain=1#L45) helps with configuring Hera-Workflows with Argo Workflows, however, it could be more clear that it is necessary for `--auth-mode=server` or `--auth-mode=client` to be set in order for Bearer tokens to be used.  

In my particular use-case, we started off setting only `--auth-mode=sso` since my team is/was using Couler and all Workflow submissions were happening inside the platform that Argo Workflows is deployed in (recent adopter of Argo - recently ditching KubeFlow and it's dsl framework as it was more than we needed in our platform).

**Comment by flaviuvadan** [comment]
Thank you for bringing this up @BnJam! Sounds like a great suggestion. Any chance you are open to submitting a PR? I am sure it may help many users who use Hera in a similar setup to yours! :)

**Comment by BnJam** [comment]
I can submit a PR for this :)
