### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by xuanbo241** [argoproj-labs/hera-workflows#396]
Hello
    I am try to submit flow to argo with the following codes:
argo-workflows                      6.3.5

from hera import Task, Workflow
from hera import global_config

global_config.GlobalConfig.host = xxx
global_config.GlobalConfig.token = xxx
global_config.GlobalConfig.verify_ssl = False

def say(message: str):
     print(message)

with Workflow("diamond") as w:
    a = Task('a', say, ['This is task A!'])
    b = Task('b', say, ['This is task B!'])
    c = Task('c', say, ['This is task C!'])
    d = Task('d', say, ['This is task D!'])
    a >> [b, c] >> d

w.create()

when i run this scrpt , i got the following error:
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xxx', port=xxx): Max retries exceeded with url: /api/v1/workflows/default (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

My question is why i get a ssl error after i set `global_config.GlobalConfig.verify_ssl = False`?

It seems that set ssl by GlobalConfig is not work...

And i try to change the source code of hera/workflow_service.py:
class WorkflowService:
def __init__(
        self,
        host: Optional[str] = None,
        verify_ssl: bool = False,  # change True to False
        token: Optional[str] = None,
        namespace: Optional[str] = None,
    ):
After i change the default value of verify_ssl from True to False, i can submit to Argo server successfully.

So is it a bug or something that `global_config.GlobalConfig.verify_ssl` does not affect "WorkflowService"'s verify_ssl?

Thanks

**Comment by flaviuvadan** [comment]
Thank you for reporting this @xuanbo241! Any chance you can try out #398 to see if it helps?

**Comment by xuanbo241** [comment]
Hi @flaviuvadan,
    Thank you for your response.
    I have tried  https://github.com/argoproj-labs/hera-workflows/pull/398, but it still not work...
    From https://github.com/argoproj-labs/hera-workflows/pull/398, i see 2 changes:
    -- change __get_config to _get_config in config.py; 
        but how does this change affect WorkflowService?
    -- add Optional in WorkflowService' verify_ssl
        but its default value is still True, and it seems no pass from GlobalConfig to WorkflowService instantiation？

I try followings according to my understanding, and it works:
workflow.py: add 'verify_ssl=GlobalConfig.verify_ssl' in WorkflowService instantiation:
`@property
    def service(self: WorkflowType) -> WorkflowService:`
        `    if self._service is None:`
            `        self._service = WorkflowService(verify_ssl=GlobalConfig.verify_ssl)`
        `    return self._service`

**Comment by flaviuvadan** [comment]
That's a better idea than that what I have posted in this PR. I will change it! Thank you for the thoughts @xuanbo241!

**Comment by flaviuvadan** [comment]
Adjusted the PR @xuanbo241
