### ISSUE TITLE
Expose `verify_ssl` and `scheme` on `Configuration`

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/hera-workflows#40]
Multiple users wish to use Hera but have control over certificate checking behavior by controlling the scheme and SSL verification configuration of Hera. Hera needs to expose the `verify_ssl` flag, along with allowing users to specify their preferred scheme, and domain fully.

**Comment by dixon1e** [comment]
@flaviuvadan I am so sorry for dropping off the radar on this. COVID related events have hit our world very hard, as well as the Colorado fires. We appreciate your efforts so much.

A quick favor to ask? Can you add "hello world" examples to the repo demonstrating how to use the options we've just created?

**Comment by dixon1e** [comment]
Just did a quick smoke test and it worked. Working up some more complex use cases. Brilliant, thank you!

**Comment by flaviuvadan** [comment]
> @flaviuvadan I am so sorry for dropping off the radar on this. COVID related events have hit our world very hard, as well as the Colorado fires. We appreciate your efforts so much.
> 

No worries at all! Yes, they have, and with everything happening around COVID and the fires I am only sending good thoughts to Colorado ❤️ 

> A quick favor to ask? Can you add "hello world" examples to the repo demonstrating how to use the options we've just created?

Yes, definitely!

> Just did a quick smoke test and it worked. Working up some more complex use cases. Brilliant, thank you!

Glad this is settled! My pleasure 🙂 

> The imports are changed. Also showed usage of a different namespace to execute, and the verify_ssl flag

👍🏻
