### ISSUE TITLE
Calling a workflow from within itself using Hera to avoid argo workflows crash for very large workflows (20,000+ pods)

### ISSUE THREAD

**Issue by abhishektvz** [argoproj-labs/hera-workflows#404]
Hi team,
if I try to use w.to_yaml inside the Workflow context to create a task to submit the workflow, it doesn't work.
We have a backfill that we want to run, but even with parallelism set to a smaller value, the overall number of tasks crashes the argo workflows server hence we came up with this method, but this is not working either,

Any suggestions ?

**Comment by Trollgeir** [comment]
`w.to_yaml()` isn't possible before the context is closed (it cannot create a yml before you've finished declaring the workflow).

Have you looked into[ cron-backfills in argo](https://argoproj.github.io/argo-workflows/cron-backfill/)? We do support `with_sequence` in Hera.
