### ISSUE TITLE
Documentation not showing version

### ISSUE THREAD

**Issue by danielc103** [argoproj-labs/hera-workflows#405]
https://hera-workflows.readthedocs.io/en/latest/

Showing `0.0.0-dev` and missing source code documentation for some modules,

example

https://hera-workflows.readthedocs.io/en/latest/_modules/hera/workflow.html#Workflow

**Comment by flaviuvadan** [comment]
Thank you for identifying this @danielc103! This is a relic of introducing automated versioning in Hera's release process. [The version is set here](https://github.com/argoproj-labs/hera-workflows/blob/main/docs/conf.py#L9). We can probably replace it with the "installed" Hera version from the venv? Thoughts?

**Comment by danielc103** [comment]
Not too familar with this kind of version setting with Python. I can take a look to see if there is a an easy way to pull that version into `conf.py` from the venv.
