### ISSUE TITLE
Input Param Templating vs Inlining

### ISSUE THREAD

**Issue by jsmodic** [argoproj-labs/hera-workflows#406]
I'm jumping into both Argo Workflows and Hera concurrently and I'm trying to understand the Hera way to do template inputs. Consider the following two examples:

```
with WorkflowTemplate("workflow", parameters=[Parameter("param")]) as wf:
    task1 = Task("task1", image="foo", command="bar", args=[wf.get_parameter("param")])
```

vs

``` 
with WorkflowTemplate("workflow", parameters=[Parameter("param")]) as wf:
    task1 = Task("task1", image="foo", command="bar", args=["{{inputs.parameters.param}}"], inputs=[wf.get_parameter("param")])
```

The latter will create a generic template like I'd expect from the Argo docs. My naive expectation was for these to be basically equivalent, but they are not.

Basically, I'm wondering what the Hera-y way to template inputs like this is? Does Hera have a better way to generate "inputs.parameters.param" for me that I'm missing?

**Comment by flaviuvadan** [comment]
Hi @jsmodic! The `args` are actually container startup command parameters. Is that what you are trying to set? Or, are you trying to set an optional input parameter to the task, passed via global parameters, which is the first example?

**Comment by jsmodic** [comment]
Hi @flaviuvadan. Yeah, in both cases I'm just trying to template the args to a container via global parameters. I'm trying to get a handle on the most "Hera" way to write things.

The Argo docs would suggest using the latter style with "inputs.parameters.param" and inputs, but there's no real way to generate that in Hera without writing it out manually as in my example.

I'm just wondering if there's any real reason Hera prefers the former style.

**Comment by jsmodic** [comment]
That does make intent more obvious. Thank you.

(Per this specific issue, I just extended 'Parameter(name="foo")' to just have a method to generate "inputs.parameters.foo" anyways.)
