### ISSUE TITLE
Setting failedJobsHistoryLimit and successfulJobsHistoryLimit

### ISSUE THREAD

**Issue by zevektor** [argoproj-labs/hera-workflows#416]
Hello,

I am trying to generate a workflow using Hera, and want to change how many failed/successful runs should be retained. 

I cannot find how to set these properties in a Workflow or CronWorkflow:
- successfulJobsHistoryLimit
- failedJobsHistoryLimit

Are these attributes not supported? 

Thanks

**Comment by flaviuvadan** [comment]
Hi @zevektor! This is currently missing in Hera and would have to be added to the `CronWorkflow.__init__` and `build`. Any chance you are open to a PR? 🙂 We are also working on auto-generating all the models via Pydantic currently, so all the features of Argo will come in Hera out of the box. That will happen in a few weeks if you are willing to wait and skip the PR!

**Comment by flaviuvadan** [comment]
Hey @zevektor! We just released 5.0.0rc1, which has feature parity with Argo Workflows! You will now see [failed jobs history limit](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/workflows/cron_workflow.py#L28) and [successful jobs history limit ](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/workflows/cron_workflow.py#L31) 🎉 Let me know how this works for you
