### ISSUE TITLE
PodDisruptionBudget

### ISSUE THREAD

**Issue by alejoGT1202** [argoproj-labs/hera-workflows#417]
Argo supports `PodDisruptionBudgetSpec` to create a `PDB` for a workflow. I was wondering if using Hera is possible to specify this on the workflow and if not is there a way I can implement it using the native Argo library?

**Comment by flaviuvadan** [comment]
@alejoGT1202 we just released 5.0.0rc1, which comes with [PDB on workflow](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/workflows/workflow.py#L105)! 🎉
