### ISSUE TITLE
Hera volumes are incomplete and not extendible

### ISSUE THREAD

**Issue by instauro** [argoproj-labs/hera-workflows#435]
Hera currently supports a subset of the [Argo Workflow volumes](https://github.com/argoproj/argo-workflows/blob/6c432d2c980bd37be28ebb22d1e83b176993ce38/sdks/python/client/argo_workflows/model/volume.py#L147-L175), which is ExistingVolume, SecretVolume, EmptyDirVolume and ConfigMapVolume. The implementations are thin wrappers with build methods, which are then built in _build_persistent_volume_claims in [task.py](https://github.com/argoproj-labs/hera-workflows/blob/7e71811f3a87d6a434e98f97d6eea245bef0012c/src/hera/task.py#L910-L919). The isinstance check for each whitelisted class is very problematic since it stops the users from implementing the missing volume-types on their own.

A possible solution could be to have a common baseclass for the Argo volumes which then could be used in the isinstance check.

**Comment by flaviuvadan** [comment]
Thanks for reporting this @instauro! Yea, it's certainly a problem at the moment.. we are currently working on getting feature parity with Argo Workflows and Events via Hera V5. That one has [all the volumes implemented](https://github.com/argoproj-labs/hera-workflows/blob/a54f9d29ae453e280b6091199b7c6f70b3c72f9b/src/hera/volumes.py) and it follows your suggestion of extending some [base class that offers users the flexibility of creating their own volumes as well](https://github.com/argoproj-labs/hera-workflows/blob/a54f9d29ae453e280b6091199b7c6f70b3c72f9b/src/hera/volumes.py#L88). That's not the PR that will ultimately be merged as we decided to break apart the work a bit (there are multiple V5 PRs open). The branch that contains the volumes has exactly a copy of the file above, which introduces all the volumes and the base class. The plan is to support V4 going forward so, if you are open to it, are you interested in contributing some of the missing volumes in V4? :)

**Comment by flaviuvadan** [comment]
@instauro we just released 5.0.0rc1, which [has all the volume implementations](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/workflows/volume.py)! 🎉
