### ISSUE TITLE
Feature request: support for Workflow.spec.podGC

### ISSUE THREAD

**Issue by mkotsalainen** [argoproj-labs/hera-workflows#436]
This should be useful when debugging failed workflows

https://argoproj.github.io/argo-workflows/fields/#podgc
https://github.com/argoproj/argo-workflows/blob/master/examples/pod-gc-strategy.yaml

**Comment by flaviuvadan** [comment]
Hello @mkotsalainen! Thank you for the issue submission. This feature is coming soon, in Hera v5, as it will contain all the Argo Workflows models. Here's [PodGC](https://github.com/argoproj-labs/hera-workflows/blob/1f55a7ed48c246ddaec454ee9b82a4af98e0ff63/src/hera/workflows/models/io/argoproj/workflow/v1alpha1.py#L1162), for instance

**Comment by flaviuvadan** [comment]
@mkotsalainen we just released 5.0.0rc1, which has [PodGC](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/workflows/workflow.py#L106) available on Workflow 🎉
