### ISSUE TITLE
Hera version 4.4.1 seems to have broken Sequence

### ISSUE THREAD

**Issue by varunm22** [argoproj-labs/hera-workflows#444]
With the 4.4.1 update, our code using `Sequence` in `Task` started giving the following error: 
```
ValueError: `with_param` or `with_sequence` items are utilized in inputs, nor could they be deduced
```
I tried running the Sequence example present in the repo at https://github.com/argoproj-labs/hera-workflows/blob/main/examples/with_sequence.py and it fails with the same error message, leading me to believe this is a bug. If this was actually an intended chance, can you update the example so I can see what I need to change in our own code to get it working?

**Comment by flaviuvadan** [comment]
Thanks for reporting this @varunm22! I will take a look at it. Was this ok in 4.4.0 in your use case?

**Comment by varunm22** [comment]
Thanks for taking a look @flaviuvadan! To be honest, I'm not completely sure because I didn't notice it until we were on 4.4.1, and I know we were previously on 4.3.1. Either our dependency manager jumped directly to 4.4.1 or it was working fine in 4.4.0.

**Comment by flaviuvadan** [comment]
@varunm22 I think we identified the issue and fixed it in 4.4.2. Going to close this for now. Of course, feel free to reopen if 4.4.2 does not fix it!

**Comment by varunm22** [comment]
Thank you, I will let you know if we have any future issues!

**Comment by varunm22** [comment]
@flaviuvadan I noticed the structure of the examples also changed. Do you know where the Sequence example is now? It seems to have disappeared from the repo

**Comment by varunm22** [comment]
@samj1912 Thanks! I'll reference this site going forward vs looking directly in the examples dir
