### ISSUE TITLE
Boolean logic DAG dependencies

### ISSUE THREAD

**Issue by alejoGT1202** [argoproj-labs/hera-workflows#446]
Hello,

According to Argo [documentation](https://argoproj.github.io/argo-workflows/enhanced-depends-logic/), boolean logic operators are available for setting dependencies between tasks in a DAG. I was wondering if this can be done with hera. For example I have tasks A,B,C,D and I would like to execute to do the following logic in the dag

`[A,(B or C)] >> D`

**Comment by flaviuvadan** [comment]
Hello @alejoGT1202! Thanks for the question! You have access to the `depends` fields on `Task`, so you can set up whatever custom logic is necessary for your use case. However, I think it would be very nice for Hera to have this type of enhanced logic available :) I will mark this as an enhancement in addition to a question

**Comment by flaviuvadan** [comment]
Hey @alejoGT1202! See #518 :)
