### ISSUE TITLE
Passing outputs from one step/task to the inputs of another

### ISSUE THREAD

**Issue by mshatkhin23** [argoproj-labs/hera-workflows#498]
In hera v4 I remember we had a well documented way of doing the above.  Something like:
```
task1 = Task(..., outputs=Parameter("output1", "hey"))
task2 = Task(..., inputs=Parameter("input1, task1.get_parameter("output1").value))
```

I'm not seeing any examples that show the same for v5.  The closest I've found is [here](https://github.com/argoproj-labs/hera-workflows/blob/main/examples/workflows/resource_flags.py#L35) which uses Argo simple expression syntax directly.  Can we add some documentation on best practices for this? 

(happy to contribute an example after input from v5 designers on how they thought about this)

**Comment by elliotgunton** [comment]
Yeah currently the only syntactic sugar we have is for task results here https://github.com/argoproj-labs/hera-workflows/blob/af275245fb37206df15267c3a97a4511a5859118/src/hera/workflows/task.py#L81

We're aiming for syntactic sugar improvements like this for subsequent patches/minor versions but we might be able to add this today 🚀
