### ISSUE TITLE
The documentation does not correspond to library

### ISSUE THREAD

**Issue by MarkPorohnja** [argoproj-labs/hera-workflows#503]
Hello!

I have a problem with using hera-workflows library (currently 4.4.2). In your examples and documentation to import library objects you add for example `from hera.workflows import DAG, Container, Parameter, Workflow` but it my case there is no workflows directory:

![image](https://user-images.githubusercontent.com/43471024/227473153-af413af1-00c4-454a-8e01-a9c47d7cad84.png)

To be able to import some objects I need to use not `workflows` but `workflow`:
![image](https://user-images.githubusercontent.com/43471024/227473434-ab4afa59-bce0-44d3-acf2-656ed5847b13.png)

but it still has problems...

requirements.txt: `hera-workflows==4.4.2`

could you please elaborate what is wrong and how to fix it. Otherwise the use of your documentation becomes inconsistent

**Comment by Zhaikuku** [comment]
hi, this is doc for  hera-workflows==4.4.2  -> https://github.com/argoproj-labs/hera-workflows/tree/4.4.2

**Comment by MarkPorohnja** [comment]
@Zhaikuku
It seems that was looking at the docs of the main branch...
Thanks

**Comment by elliotgunton** [comment]
@Zhaikuku thank you for answering!

@MarkPorohnja we are looking to add versioned documentation for our readthedocs, so hopefully it will be more obvious in future. For now, yes the 4.4.2 docs are on the 4.4.2 tagged release branch. We are in the middle of putting v5.0.0 together so we moved over on the main branch.

**Comment by samj1912** [comment]
@MarkPorohnja we have versioned hera docs available now.

v5 docs are available at https://hera-workflows.readthedocs.io/en/latest/ and v4 docs are available at https://hera-workflows.readthedocs.io/en/v4
