### ISSUE TITLE
problems with v1.0.0 package published to pypi

### ISSUE THREAD

**Issue by harelwa** [argoproj-labs/hera-workflows#51]
Hi,

Something is wrong with the wheels / pypi package published.

Here is the way to inspect / reproduce:

```bash
> docker run -it --rm continuumio/miniconda3
> conda create -n py37-env python=3.7 pip -y
[...]
> conda activate py37-env
(py37-env) > pip --version
pip 21.2.2 from /opt/conda/envs/py37-env/lib/python3.7/site-packages/pip (python 3.7)
(py37-env) > pip install hera-workflows==1.0.0
[...]
(py37-env) > python -c "import hera"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'hera'
(py37-env) > ls /opt/conda/envs/py37-env/lib/python3.7/site-packages/ | grep hera
hera_workflows-1.0.0.dist-info
# here the actual package is missing, e.g. with `pydantic` you'll get 
(py37-env)  > ls /opt/conda/envs/py37-env/lib/python3.7/site-packages/ | grep pydantic
pydantic
pydantic-1.9.0.dist-info
```

The above issue is also the cause of the `conda-forge` feedstock CI failing - 

https://github.com/conda-forge/hera-workflows-feedstock/pull/2

Many thanks,
Harel

**Comment by flaviuvadan** [comment]
Hey @harelwa! Thank you for submitting this. I will take a look soon!

**Comment by flaviuvadan** [comment]
Please see: https://github.com/argoproj-labs/hera-workflows/pull/52

**Comment by flaviuvadan** [comment]
@harelwa I just installed 1.0.1 in a virtual environment through `pip install hera-workflows==1.0.1`. Unfortunately 1.0.0 will remain broken on PyPi 🙁  What's the best way to help conda-forge in a case like this? 

I must apologize for not catching this earlier. It's evident that Hera needs a step that publishes it to Test PyPi prior to the official PyPi index.

**Comment by harelwa** [comment]
Hi @flaviuvadan 

Thank you very much for the [so]fast reply and fix!

as for `conda-forge` -- 

no worries. it did not publish due to the tests failure. I will update the recipe to look at `v1.0.1`.

please note that this err was caught by `conda-forge` ci, as `conda build` runs tests *of the built package*. you can see more here - <https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#test-section>

As for `hera`s CI, you can indeed check this too, prior to publishing, by adding a step of `test-pkg` step between `build` + and `publish`.

This `test-pkg` will do something like - 

-  install the local built `.whl` in a **new venv** [ "test env" ]
- install additional pkgs required for testing, e.g. `pytest`
- run tests [ `pytest tests` ]
  In this context -- make sure to not fall into `pytest` PYTHONPATH pitfalls - <https://docs.pytest.org/en/6.2.x/pythonpath.html>

hth,
harel

**Comment by harelwa** [comment]
**update**

`conda-forge/hera-workflows-feedstock` PR for **v1.0.1** merged:

<https://github.com/conda-forge/hera-workflows-feedstock/pull/3>

@flaviuvadan  - I've added the tests to run as part of the feedstock ci pipelines [ previously only `imports` tests ran there ]:

https://github.com/conda-forge/hera-workflows-feedstock/blob/master/recipe/meta.yaml#L39

`hera-workflows=1.0.1` is now available in `conda-forge`:

<https://anaconda.org/conda-forge/hera-workflows>

**Comment by flaviuvadan** [comment]
@harelwa that's great! Thank you for submitting this issue, giving suggestions on how to improve the safety of Hera's releases, and your documentation PR 🙂  I am going to close this issue but feel free to submit other issues, or reopen this one if there's more to discuss.
