### ISSUE TITLE
question - is there kind of cron task api in hera

### ISSUE THREAD

**Issue by ni-todo-spot** [argoproj-labs/hera-workflows#6]
Hello all!
I'm considering using hera for my project's scheduling purposes.

As so I was wondering if there is an API for creating scheduled/cron/timed tasks?

Thanks in advance!

**Comment by flaviuvadan** [comment]
> Hello all! I'm considering using hera for my project's scheduling purposes.
> 
> As so I was wondering if there is an API for creating scheduled/cron/timed tasks?
> 
> Thanks in advance!

Hi @ni-todo-spot! Thanks for the question and great to hear you're considering the use of Hera! 

Currently, Hera does not have full feature parity with Argo Workflows. The first release only offers graph workflow submission as we wanted to see the community response and add features based on that 🙂  However, adding a basic `CronWorkflow` type, similar to the `Workflow` [one](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/v1/workflow.py#L15), as a wrapper around [V1alpha1CronWorkflow](https://github.com/argoproj-labs/argo-client-python/blob/master/docs/V1alpha1CronWorkflow.md) with the corresponding [service](https://github.com/argoproj-labs/argo-client-python/blob/master/docs/CronWorkflowServiceApi.md#createCronWorkflow) added to the [WorkflowService](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/v1/workflow_service.py#L9). 

Would you like to contribute to implementing this? 🙂

**Comment by ni-todo-spot** [comment]
@flaviuvadan Thanks for your quick response!
I can not guarantee that I'll get to it soon, but If I choose using hera I'll definitely give it a try.

If I'm the only one who seeks this kind of feature - please do not waste any of your precious time on me :)

Thank you very much!

**Comment by flaviuvadan** [comment]
> @flaviuvadan Thanks for your quick response! I can not guarantee that I'll get to it soon, but If I choose using hera I'll definitely give it a try.
> 
> If I'm the only one who seeks this kind of feature - please do not waste any of your precious time on me :)
> 
> Thank you very much!

I am sure this is something others will want as well so let me try to get to it this week and ping you once it's done!

**Comment by ni-todo-spot** [comment]
Sounds awesome 👏

**Comment by ni-todo-spot** [comment]
Actually I'm on it as we speak 😄 
I'll open a pr once I'm done.

**Comment by flaviuvadan** [comment]
> Actually I'm on it as we speak 😄 I'll open a pr once I'm done.

Amazing, looking forward to the PR! 🚀

**Comment by NI1993** [comment]
created this - https://github.com/argoproj-labs/hera-workflows/pull/9 
from personal account

**Comment by flaviuvadan** [comment]
Solved by #9. Thank you @NI1993! 🎉
