### ISSUE TITLE
Example for using container with input and output

### ISSUE THREAD

**Issue by xiaolan-hao-tang** [argoproj-labs/hera-workflows#64]
Could anyone provide an example of using container with input and output artifacts? I'm trying to see how to get output from task1 and save it as input for task2.
Open to any suggestions.
Thanks!

**Comment by flaviuvadan** [comment]
Hi @xiaolan-hao-tang! 🙂  Would the [input/output/fanout example](https://github.com/argoproj-labs/hera-workflows/blob/main/examples/artifact_with_fanout.py) help here? It showcases how to set up an output artifact from a task, a task that uses that, then another final task that consumes whatever the output of that artifact, through the previous task, is.

**Comment by flaviuvadan** [comment]
Hey @xiaolan-hao-tang! Hope the answer helped. I am going to close this for now but please let me know if you have additional questions! Would love to hear about your use case 🙂
