### ISSUE TITLE
Migrate Hera to newly generate Argo Workflows OpenAPI client

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/hera-workflows#7]
Currently, Hera builds on top of the now deprecated/archived [argo-client-python](https://github.com/argoproj-labs/argo-client-python). This client has moved to the main Argo Workflows repository [here](https://github.com/argoproj/argo-workflows/tree/master/sdks/python). Hera's constructs and imports should migrate to the new client. A new minor version should be generated ~- 0.0.0 -> 0.1.0 -~ as a dependency will be removed, another one introduced, but the interface does not change, only internals.

**Comment by flaviuvadan** [comment]
Now that https://github.com/argoproj/argo-workflows/pull/7363 was merged, we can start thinking about migrating to the new SDK when a new Argo release is performed.

**Comment by bobh66** [comment]
I could really use this change as I have a problem with the current SDK that won't be fixed.   It validates the CronWorkflowStatus object that is returned in the create response for CronWorkflow, and it "fails" validation because the "active" attribute is None (since no cronjobs have run yet) which causes a KeyError exception even though the object was created successfully.

Is the new SDK available in pypi?  I didn't see anything from a quick search.  If you can point me in the right direction I'll see what I can put together.

**Comment by bobh66** [comment]
I should have looked further to see that you started it - let me know if I can be of any help.

**Comment by flaviuvadan** [comment]
Hey @bobh66! There's a whole story to the initial effort to migrate. [Here's](https://github.com/argoproj-labs/hera-workflows/pull/46) the PR that attempted a second migration. The problem is that PyPi does not allow setting a dependency on a repo (as is currently the case with the new SDK). After a discussion with @terrytangyuan it's a bit unclear when the next release of Argo Workflows will take place, which inhibits the official release of the SDK. However, we've discussed using my fork of Argo Workflows, after it's up to date with the latest main branch of [Argo Workflows](https://github.com/argoproj/argo-workflows), to create a release candidate as `6.0.0rc0`, install that in Hera, and perform the migration. This will give us all the objects that are required, allow us to fix the problem you noticed with cron workflows, and allows us to just relock Hera to use the official SDK post publication to PyPi. Note that both `6.0.0rc0` and `6.0.0` would be officially released to PyPi, not to some projects that I am the sole owner of 🙂  I will try my best to get this done this upcoming weekend.

**Comment by flaviuvadan** [comment]
6.3.0rv2 was just released: https://pypi.org/project/argo-workflows/6.3.0rc2/ Will perform the migration this week and have a release candidate for Hera.
